# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: appdemo
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    profiles:
      - ''
      - prod
